import type {Agent} from "../../../services/kernel/src/agent";
import {tools} from "../../../services/kernel/src/agent";

const Coder:Agent={

  name:"coder",

  async execute(task){

    console.log("[Coder]",task.action);

    await tools.workspace.writeFile(
      "workspace/output.txt",
      "Generated by AI\n"+JSON.stringify(task.payload,null,2)
    );

  }

};

export default Coder;
